point_filter_num: 5
feature_ds_leaf_size: 0.4
max_iterations: 5
cube_length: 1000
delete_range: 100
lidar_min_distance: 0.1
lidar_max_distance: 50.0
gyro_cov: 0.01
accel_cov: 0.02
gyro_bias_cov: 0.001
accel_bias_cov: 0.005
keyframe_adding_threshold: 1.0