lidar:
  -
    name: A                        # LiDAR Name  - A, B, C, D,
    topic: /livox/lidar        # LiDAR Topic
    frame: livox                 # LiDAR Frame ID
    format: LIVOX     # LiDAR Format  - RSLIDAR, VELODYNE, LIVOX, OUSTER, SURESTAR, RS_PACKET_RSHELIOS_16P, RS_PACKET_RSHELIOS
    purpose: LIO
    use: true                
    major: true
    
imu:
  topic: /imu/data
  frame: imu
  use: true

wheel:
  topic: /wheel_odometry
  frame: wheel
  use: false

gnss: 
  topic: /gps
  frame: gps
  use: false