mode: LIM        # Mapping Mode : LIM , LOM , PLM
params: 
  -
    type: SENSOR # Param Type : SENSOR, EXTRINSIC, LIMAPPING
    file: sensor_param.yaml
  -
    type: EXTRINSIC # Param Type : SENSOR, EXTRINSIC, LIMAPPING
    file: extrinsic_param(aolu-10).yaml
  -
    type: LIMAPPING # Param Type : SENSOR, EXTRINSIC, LIMAPPING
    file: lidar_imu_mapping_param.yaml
  - 
    type: FASTLIO
    file: fast_lio_param.yaml