knot_distance: 0.1
update_every_k_knot: 1
point_filter_num: 3
lidar_min_distance: 2.0
lidar_max_distance: 80.0
feature_leaf_size: 0.1
keyframe_adding_time_threshold: 10
keyframe_adding_distance_threshold: 1.0
keyframe_adding_angle_threshold: 1.0
keyframe_mapping_downsample_size: 1.0
lidar_weight: 1.0
global_velocity_weight: 1.0
initial_window_length: 0.75
imu_excite_threshold: 0.30
grvity_norm: 9.81
imu_frequency: 200
imu_accel_noise: 9.6e-03
imu_gyro_noise:  3.4e-03
imu_accel_bias_noise: 6.4356659353532566e-05
imu_gyro_bias_noise: 3.5640318696367613e-05