num_ring: 32
num_horizon: 1800
num_of_cores: 4
edge_threshold: 1.0
surf_threshold: 0.1
surf_feature_leaf_size: 0.2 
lidar_min_distance: 1.0
lidar_max_distance: 80.0
match_method: LOAM    # Match Method : LOAM , FAST_LOAM
corner_ds_leaf_size: 0.2
surface_ds_leaf_size: 0.4
corner_feature_min_valid_num: 10
surface_feature_min_valid_num: 100
keyframe_search_radius: 30
keyframe_adding_distance_threshold: 1.0
keyframe_adding_angle_threshold: 1.0
keyframe_mapping_downsample_size: 1.0
auto_loop_closure: false
loop_closure_searching_distance: 10
loop_closure_distance_interval: 15.0
loop_closure_score_threshold: 0.1
mono_layer_motion: true
initial_window_length: 0.75
imu_excite_threshold: 0.35
grvity_norm: 9.81
imu_accel_noise: 9.6e-03
imu_gyro_noise:  3.4e-03
imu_accel_bias_noise: 6.4356659353532566e-05
imu_gyro_bias_noise: 3.5640318696367613e-05
map_resolution: 0.1