mode: LIM        # Mapping Mode : LIM , LOM , PLM , CLINS
params: 
  -
    type: SENSOR # Param Type : SENSOR, EXTRINSIC, LIMAPPING
    file: sensor_param.yaml
  -
    type: EXTRINSIC # Param Type : SENSOR, EXTRINSIC, LIMAPPING
    file: extrinsic_param.yaml
  -
    type: LIMAPPING # Param Type : SENSOR, EXTRINSIC, LIMAPPING
    file: lidar_imu_mapping_param.yaml
  -
    type: CLINS # Param Type : SENSOR, EXTRINSIC, LIMAPPING
    file: clins_param.yaml
  - 
    type: FASTLIO
    file: fast_lio_param.yaml
  - 
    type: POSEGRAPH
    file: pose_graph_param.yaml
  - 
    type: TINYLOCATION
    file: tiny_location_param.yaml
