point_filter_num: 5
feature_ds_leaf_size: 0.5
max_iterations: 3
cube_length: 1000
delete_range: 100
lidar_min_distance: 1.0
lidar_max_distance: 100.0
gyro_cov: 0.1
accel_cov: 0.1
gyro_bias_cov: 0.001
accel_bias_cov: 0.001
keyframe_adding_threshold: 1.0