lidar:
  -
    name: A                           # LiDAR Name  - A, B, C, D,
    topic: /pmtd_1/lidar/cloudxyzit        # LiDAR Topic
    frame: rslidar                          # LiDAR Frame ID
    format: VELODYNE            # LiDAR Format  - RSLIDAR, VELODYNE, LIVOX, OUSTER, SURESTAR, RS_PACKET_RSHELIOS_16P, RS_PACKET_RSHELIOS
    purpose: LIO
    use: true                
    major: true
    
imu:
  topic: /mc2132_imu_data
  frame: imu
  use: true

wheel:
  topic: /wheel_odometry
  frame: wheel
  use: false

gnss: 
  topic: /gps
  frame: gps
  use: false