lidar:
  -
    name: A                        # LiDAR Name  - A, B, C, D,
    topic: /rslidar_packets        # LiDAR Topic
    frame: rslidar                 # LiDAR Frame ID
    format: RS_PACKET_RSHELIOS     # LiDAR Format  - RSLIDAR, VELODYNE, LIVOX, OUSTER, SURESTAR, RS_PACKET_RSHELIOS_16P, RS_PACKET_RSHELIOS
    purpose: LIM
    use: true                
    major: true
  -
    name: B
    topic: /rslidar_points
    frame: rslidar
    format: RSLIDAR
    purpose: LIO
    use: true
    major: false
    
imu:
  topic: /mg201_imu
  frame: imu
  use: true

wheel:
  topic: /wheel_odometry
  frame: wheel
  use: false

gnss: 
  topic: /gps
  frame: gps
  use: false