lidar:
  -
    name: A                   # LiDAR Name  - A, B, C, D,
    topic: /rslidar_points    # LiDAR Topic
    frame: rslidar            # LiDAR Frame ID
    format: RSLIDAR           # LiDAR Format  - RSLIDAR, VELODYNE, LIVOX, OUSTER, SURESTAR, RS_PACKET_RSHELIOS_16P, RS_PACKET_RSHELIOS
    use: true                
    major: true
  -
    name: B
    topic: /rslidar_topic
    frame: rslidar
    format: RSLIDAR
    use: false
    major: false
    
imu:
  topic: /imu/data
  frame: imu
  use: true

wheel:
  topic: /odom
  frame: wheel
  use: false

gnss: 
  topic: /gps
  frame: gps
  use: false